### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Darcy-007** [Roommate-Budget-Helper/RBH-Frontend#11]
After this issue, no other issue should have form validation as an acceptance criterion. Form validation should be implemented in every form in the frontend. Including invalid input, duplicated input, and blank input. To achieve this in angular, the best way to do it is to use the built-in validators in the angular-form package: some of them can be used directly, others can be customized by ourselves.

**Acceptance Criteria**
- [x] Form validation implemented in every form.

**Comment by zisaanlau** [comment]
Finished
