### ISSUE TITLE
Frontend Testing with MatDialogRef

### ISSUE THREAD

**Issue by lanxikk** [Roommate-Budget-Helper/RBH-Frontend#13]
I am having a hard time writing tests for frontend forms. We used matdialog and mat errors for form validation, but i have no idea on how to import matDialogRef to my component tests.

Bug Report: 
![image](https://user-images.githubusercontent.com/49965627/70936451-4d7fad00-2010-11ea-9196-8b5a25c45fad.png)

Test Code:
![image](https://user-images.githubusercontent.com/49965627/70936494-625c4080-2010-11ea-8bde-ab6f86c2a992.png)

**Comment by lanxikk** [comment]
Any one has any ideas?

**Comment by lanxikk** [comment]
@pastorsj

**Comment by pastorsj** [comment]
@lanxikk What branch are you on?

**Comment by pastorsj** [comment]
https://stackoverflow.com/questions/48058457/failed-cant-resolve-all-parameters-for-matdialogref-unit-testing-a

**Comment by lanxikk** [comment]
@pastorsj Thanks! It works now.

**Comment by lanxikk** [comment]
Solved Issue
