### ISSUE TITLE
Test for routes

### ISSUE THREAD

**Issue by lanxikk** [Roommate-Budget-Helper/RBH-Frontend#17]
Unit testing for routing in milestone 2 should be implemented

**Comment by lanxikk** [comment]
Does anybody know what does this error message mean? 
I created a spy on ApiClient.auth.login and gave it a fake return value, but I got this error message logged on the console. 
![4d00cae7adc264d1cbab5d324a56ad8](https://user-images.githubusercontent.com/49965627/71864882-21b38c80-30cf-11ea-80b5-ef09c7bb4502.png)
 
![image](https://user-images.githubusercontent.com/49965627/71864535-072ce380-30ce-11ea-9758-bd6d8cd5437e.png)

**Comment by Darcy-007** [comment]
I have no idea @pastorsj
