### ISSUE TITLE
index page furnishment

### ISSUE THREAD

**Issue by Darcy-007** [Roommate-Budget-Helper/RBH-Frontend#18]
more information need to be presented on index page=.

**Acceptance Criteria**
- [ ] Every house need to be presented without messing up with css.
- [ ] Every entry need to be clickable
- [ ] Every entry need to have names of roommates shown

**Comment by Huangjz1997** [comment]
Does somebody know how to call functions defined in ts file in html?

So I want to display all the usernames inside a home in the index page, and I have a function does that for me in the ts file that returns a string of roommates. When I try to call that function inside html using interpolation, It pops out this error:
![image](https://user-images.githubusercontent.com/22082748/71786368-bbe4d900-2fd8-11ea-9d01-c16272318a40.png)

code in ts:
![image](https://user-images.githubusercontent.com/22082748/71786377-ce5f1280-2fd8-11ea-98fd-dda76a1a5a18.png)

code in html:
![image](https://user-images.githubusercontent.com/22082748/71786383-dae36b00-2fd8-11ea-887d-09d584040b0b.png)

**Comment by Huangjz1997** [comment]
@DRSisco

**Comment by DRSisco** [comment]
Async functions 🤔 I think you might prefer to return a promise. 
(If you commit your code, I can teach you a way to link directly to the code in github, so it will show up here in a code block. I'll show you guys in the meeting tomorrow)

I think you are looking to use the async pipe 
`{{getHomeByHomeId(16) | async}}`
https://angular.io/api/common/AsyncPipe

**Comment by pastorsj** [comment]
I agree with Donald here. Also, in angular, when calling a method from the html, you can’t use “this” to call the method. Just use the name of the method to call it.

**Comment by Darcy-007** [comment]
Thanks!!
