### ISSUE TITLE
Home Detail Page Model Build Up

### ISSUE THREAD

**Issue by lanxikk** [Roommate-Budget-Helper/RBH-Frontend#19]
Build the home detail page up.
**Acceptance Criteria**
- [ ] Details showed specified by the button clicked by the user from the index page.
- [ ] Looks alike to the moke up.

**Comment by DRSisco** [comment]
@Huangjz1997 referenced this as it should be closed in #20, but due to formatting it wasn't. (I since changed it) 
Should we close this issue?
